kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: IzYNXz8jvomRLhyuAJJPPTM6VypcAMswV+dXNNaw5PI=
      - identity: {}
