---
- name: Copy certificates
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: .
    mode: "755"
  with_items:
    - ca.pem
    - admin.pem
    - admin-key.pem

- name: Copy kubectl client script
  ansible.builtin.copy:
    src: "setup-kubectl.sh"
    dest: .
    mode: "755"

- name: Install kubernetes CA globally
  ansible.builtin.copy:
    src: ca.pem
    dest: /usr/local/share/ca-certificates/kubernetes-ca.crt

- name: Update CA certs
  ansible.builtin.shell: sudo update-ca-certificates
  changed_when: true

- name: Execute kubectl configuration script
  ansible.builtin.shell:
    cmd: bash -c ./setup-kubectl.sh