---
- name: Copy certificates
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: .
    mode: "755"
  with_items:
    - ca.pem
    - admin.pem
    - admin-key.pem

- name: Copy kubectl client script
  ansible.builtin.copy:
    src: "setup-kubectl.sh"
    dest: .
    mode: "755"
  notify:
    - Execute kubectl configuration script
